version: '3'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=perpetual_dex
    depends_on:
      - postgres
      - redis
    networks:
      - dex-network

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=perpetual_dex
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dex-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - dex-network

  # For frontend development
  frontend:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ../frontend:/app
    command: ["sh", "-c", "npm install && npm start"]
    ports:
      - "3000:3000"
    networks:
      - dex-network

volumes:
  postgres-data:
  redis-data:

networks:
  dex-network: 